const express = require("express");
const axios = require("axios");
const multer = require("multer");
const fs = require("fs");
const FormData = require("form-data");

const router = express.Router();
const upload = multer({ dest: "uploads/" }); // Temporary file storage

// Route to handle dataset upload
router.post("/analyze-bias", upload.single("file"), async (req, res) => {
  try {
    const file = req.file;

    // Construct form-data object
    const formData = new FormData();
    formData.append("file", fs.createReadStream(file.path));

    // Send file to Python service
    const response = await axios.post(
      "http://localhost:5001/analyze-bias",
      formData,
      {
        headers: formData.getHeaders(), // Add headers generated by form-data
      }
    );

    // Send results back to the client
    res.json(response.data);

    // Clean up uploaded file
    fs.unlinkSync(file.path);
  } catch (error) {
    console.error("Error analyzing bias:", error.message);
    res.status(500).json({ error: "Failed to analyze bias" });
  }
});

module.exports = router;
